### ISSUE TITLE
Create .exe installation

### ISSUE THREAD

**Issue by kw2019ltd** [leoafarias/sidekick#1]
hi, can you publish the app as exe for windows

**Comment by mzdm** [comment]
this might help https://pub.dev/packages/squirrel

**Comment by aguilaair** [comment]
Hey! If the #11 gets merged there will be an MSIX installer for Windows, it is not as straightforward as squirrel to install but should be good enough for the time being.

**Comment by aguilaair** [comment]
Squirrel doesn't look to difficult to implement either, might be worth a shot too. @leoafarias could you assign this issue to me, I'll try it out on companion and if it works well w/ the auto-update feature that'll roll out then we can add this as an asset and done.

**Comment by msarkrish** [comment]
@aguilaair when we can get .exe file?

**Comment by aguilaair** [comment]
Sidekick now has .MISX, I'll experiment with squirrel soon(ish) to see if we can use it

**Comment by aguilaair** [comment]
Update: Squirrel cannot currently be implemented. We'll continue to use MSIX for the foreseeable future until the NNBD migration is done and we can use it.
```
[sidekick] flutter pub get
Running "flutter pub get" in sidekick...                        
Because pubspec_yaml 2.0.1+1 depends on yaml ^2.2.0 and no versions of pubspec_yaml match >2.0.1+1 <3.0.0, pubspec_yaml ^2.0.1+1 requires yaml ^2.2.0.

And because every version of squirrel depends on yaml ^3.1.0 and every version of fvm from git depends on pubspec_yaml ^2.0.1+1, squirrel is incompatible with fvm from git.

So, because sidekick depends on both fvm from git and squirrel ^0.1.0, version solving failed.
pub get failed (1; So, because sidekick depends on both fvm from git and squirrel ^0.1.0, version solving failed.)
exit code 1
```

**Comment by leoafarias** [comment]
Tried using squirrel but this dependency thing is a pain. Probably will be part of a null safety migration

**Comment by leoafarias** [comment]
This is on the alpha4

**Comment by DonnC** [comment]
@leoafarias i know this is closed but you can check out [inno setup](https://jrsoftware.org/isinfo.php)
i use it more often to create standalone .exe files for my flutter desktop applications as installable setup files

**Comment by leoafarias** [comment]
@DonnC can you create a new issue as an enhancement so we can discuss?

Would like to know the benefits over the current setup.
