### ISSUE TITLE
App doesn't work in macOS without access permission to Documents 

### ISSUE THREAD

**Issue by osaxma** [leoafarias/sidekick#100]
### issue:
The app doesn't work if access permission to Documents were not allowed in macOS. 

### To reproduce:

- close the app. 
- remove access permission from SideKick:
<img width="800" alt="Screen Shot 2021-06-20 at 12 31 52 AM" src="https://user-images.githubusercontent.com/46427323/122655951-44205500-d15f-11eb-96b8-f6708b4903d2.png">

- open the app again
- The app would look like:

<img width="400" alt="Screen Shot 2021-06-20 at 12 29 20 AM" src="https://user-images.githubusercontent.com/46427323/122655981-80ec4c00-d15f-11eb-9926-0fa7b40c5541.png">

### Additional info:
- System: macOS Big Sur 11.2.3 (20D91)
- SideKick: 0.1.1

---
btw, In an older version, I got this screen and saved it but I forgot to file an issue at the time. 
<img width="400" alt="Screen Shot 2021-06-11 at 4 24 23 PM" src="https://user-images.githubusercontent.com/46427323/122655972-76ca4d80-d15f-11eb-9b69-3672d4e7e473.png">

**Comment by leoafarias** [comment]
@osaxma I believe this is related to Hive default storage but not 100% sure. Will review.

**Comment by aguilaair** [comment]
Yes, this is caused because Sidekick is storing its setting in the Documents folder, @leoafarias we should consider moving to a more app-suited directory, maybe `getApplicationSupportDirectory()`
