### ISSUE TITLE
Open with IDE of choice

### ISSUE THREAD

**Issue by Adevien** [leoafarias/sidekick#111]
Would it possible to have an option to open a specific project straight into the IDE of choice?

**Comment by aguilaair** [comment]
Not right now, but this is a feature I'd definitely like to have too. Right now we can projects with VSCode or XCode, but I understand you may want other IDEs. Do you have any suggestions?

**Comment by Adevien** [comment]
Wait i didn't knew you can open with Vscode, i never seen that action being there.

**Comment by aguilaair** [comment]
The code is there for sure, however I'm unsure if it was ever implemented. I'll take a look ASAP.

**Comment by aguilaair** [comment]
I'm currently in the process of reimplementing this.

**Comment by aguilaair** [comment]
![image](https://user-images.githubusercontent.com/29983481/129549005-7110c6c3-2491-4770-8082-6caeeaa803e3.png)

**Comment by gauravmehta13** [comment]
Hi Guys, Not sure how this works but i have activated sidekick flutter dev for a project but when i open it in vs code it still shows flutter stable

**Comment by gauravmehta13** [comment]
any way to fix this? am i missing something?

**Comment by abehbatre** [comment]
please add IntelliJ and Android Studio

**Comment by aguilaair** [comment]
> please add IntelliJ and Android Studio

The issue with IntelliJ and Android Studio if I remember correctly is that they don't set a PATH, so there is no CLI command we can run to launch it. They also don't have a URL schema which launches them, like `vscode://`.

The combination means that Sidekick would have to look for the executable in each machine, but this is platform-specific and not dependable as, for example, intelliJ or AS can be intstalled through toolbox or individually.

The midpoint would be allowing the user to pick a specific executable, which shouldn't be too horrible to implement. Wdyt, @leoafarias?

**Comment by leoafarias** [comment]
I am ok with this being done, and PRs are welcome. However, would like to avoid complex implementations to detect executables and so on if possible
