### ISSUE TITLE
Add transparency to Windows and Linux

### ISSUE THREAD

**Issue by aguilaair** [leoafarias/sidekick#119]
This would bring UI parity with MacOS. We could use https://pub.dev/packages/flutter_acrylic as it seems very simple to implement

**Comment by leoafarias** [comment]
@aguilaair I think we should also add the top bar of the window using https://github.com/bitsdojo/bitsdojo_window, since that also behaves differently between mac, linux and windows.

**Comment by aguilaair** [comment]
![image](https://user-images.githubusercontent.com/29983481/139579613-9e824fcb-8b77-4982-a56e-34bace44fbcc.png)
WIP

**Comment by aguilaair** [comment]
@leoafarias could you check out how it looks on a MacOS machine?
