### ISSUE TITLE
Add ability to create projects and configure FVM

### ISSUE THREAD

**Issue by Sameerkash** [leoafarias/sidekick#135]
It would be great a new Flutter Project could be created with the option to select from fvm downloads and automatically initialized in the project. 

Also, future enhancement is the ability to install and modify options  `fvm`  CLI through sidekick, would make it an all in one awesome tool, I currently love using it, and these would be geat additions.

**Comment by aguilaair** [comment]
I'm tu8rning this into a discussion, as it seems more appropriate
