### ISSUE TITLE
Macos says the files are out of date

### ISSUE THREAD

**Issue by sarahk** [leoafarias/sidekick#137]
> “Sidekick” can’t be opened because Apple cannot check it for malicious software.
> This software needs to be updated. Contact the developer for more information.

I tried macos-0.1.1.dmg and sidekick_macos_2.5.0-stable.zip

My system: macos v11.5.2

**Comment by aguilaair** [comment]
Please check https://github.com/leoafarias/sidekick/wiki/Installing#macos
