### ISSUE TITLE
Check if Git is installed and configured

### ISSUE THREAD

**Issue by zs-dima** [leoafarias/sidekick#139]
Error on trying to download any Flutter release: `Internal Error: Could not install Beta`

I tried to reset Sidekick settings as well

![image](https://user-images.githubusercontent.com/25195453/133595045-ba0e7c39-e8ea-4eb8-9bb8-fd8dff2584be.png)

**Comment by zs-dima** [comment]
Path to Git.exe have to be set to solve it.
Could be nice to add notification about.

**Comment by aguilaair** [comment]
Going to take a stab at this
