### ISSUE TITLE
couldn't detect flutter sdk on other local drives

### ISSUE THREAD

**Issue by vamsee9** [leoafarias/sidekick#140]
I have installed flutter sdk 2.2.3 in my D drive, but this sidekick app wasn't detecting that version (2.2.3)

**Comment by aguilaair** [comment]
was it installed using FVM? Sidekick only scans for fvm-managed versions.

**Comment by leoafarias** [comment]
@vamsee9 sidekick only detects versions installed with fvm. Will close this issue, if I misunderstood the issue please create a new one.
