### ISSUE TITLE
Can't resize window on Linux

### ISSUE THREAD

**Issue by davidmartos96** [leoafarias/sidekick#15]
Hello! I have tried the Linux app and it works great, nice job!
I found an issue though, I'm not able to resize the window. I figure this is not intended because you set Size.infinite for the max window size.
It looks like that is disabling the ability to resize at all.

As you can see here the Maximize and Resize buttons are grayed out.
 
![image](https://user-images.githubusercontent.com/22084723/112620347-b0bdd900-8e28-11eb-8728-0e5eb429e3fc.png)

**Comment by aguilaair** [comment]
I've experienced the same issue too, I'll take a look a little later 👍

**Comment by aguilaair** [comment]
I've been experimenting with this and it is clear that `setWindowMinSize` & `setWindowMaxSize` are causing issues when resizing in linux, and setting either one will cause the bug to appear. The only workaround at this point in time I think is simply not setting these parameters in Linux

**Comment by aguilaair** [comment]
This is a known issue at https://github.com/google/flutter-desktop-embedding/issues/844

**Comment by davidmartos96** [comment]
@aguilaair Interesting. So does it fail also by commenting out the setMaxSize line? I thought the problem was about Size.inifnite.

**Comment by aguilaair** [comment]
> @aguilaair Interesting. So does it fail also by commenting out the setMaxSize line? I thought the problem was about Size.inifnite.

Yep, still fails AKAIK

**Comment by aguilaair** [comment]
This issue has now been solved. @leoafarias, mind closing it?

**Comment by leoafarias** [comment]
@aguilaair do you know which release channel is on? Want to make sure the lates build uses that version.

**Comment by aguilaair** [comment]
It's resolved on master, so there should be no change required. Just in case you can change https://github.com/leoafarias/sidekick/blob/main/pubspec.lock#L878 to `57a2cd88486105d3d813583339eb0e23c9bfd6d2`
