### ISSUE TITLE
“Sidekick” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by kadariyaujwal** [leoafarias/sidekick#150]
When i try to open sidekick, it gives me this warning & can't be opened.

"“Sidekick” can’t be opened because Apple cannot check it for malicious software."
"This software needs to be updated. Contact the developer for more information."

macos BigSur 11.5.2

**Comment by kadariyaujwal** [comment]
https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

followed this and issue was resolved.

**Comment by aguilaair** [comment]
For future reference, it is in the installing docs too: https://github.com/leoafarias/sidekick/wiki/Installing#macos
