### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by Errichamonda** [leoafarias/sidekick#158]
Hi, I'm trying to reinstall Sidekick on my other PC but it doesn't work. I followed the instructions and added the certificate to the Trusted Root Certification Authorities but it seems to be expired

![image](https://user-images.githubusercontent.com/17320042/146822301-0bccb456-44bf-431e-a129-a5d836b0b307.png)

**Comment by aguilaair** [comment]
Hey, I'll take a look at this in the morning!

**Comment by aguilaair** [comment]
The next version of Sidekick will release with a new (but still self-signed) certificate. Waiting on @leoafarias to see if we can push it to the Microsoft Store, which could od the signing for us.

**Comment by aguilaair** [comment]
Solved, please download Sidekick from the MS Store

https://www.microsoft.com/store/productId/9NZ54K8CW0WG
