### ISSUE TITLE
Improve automatic update for MS Store installs

### ISSUE THREAD

**Issue by aguilaair** [leoafarias/sidekick#166]
Now that Sidekick is on the MS Store, automatic updates should not be queried through the app (or at the very minimum should direct to the MS Store)

Any help in finding a way to detect MS Store installs would be appreciated, alternatively, we can just build a different version of the app depending on where it is going to be posted.

**Comment by leoafarias** [comment]
@aguilaair maybe the best way is to add a build flag when building and sending to the ms store
