### ISSUE TITLE
 Title bar does not display properly

### ISSUE THREAD

**Issue by Zhangxxl** [leoafarias/sidekick#167]
The moment it is just opened, it can be displayed normally, but soon the title bar will be covered by gray.
OS: Windows 11
![image](https://user-images.githubusercontent.com/18618523/150510430-5346020e-ab24-4ac5-b35d-e7146d1e5ed2.png)

**Comment by Zhangxxl** [comment]
download from [MS Store](https://www.microsoft.com/store/productId/9NZ54K8CW0WG)

**Comment by aguilaair** [comment]
There must be some kind of overflow happening, would you be able to build on debug mode and see what the issue is?

I am not able to replicate it

**Comment by aguilaair** [comment]
Managed to reproduce on linux:

![image](https://user-images.githubusercontent.com/29983481/152655557-2cc498a0-5fe8-4413-a6f6-18a10c7ec809.png)
 

Will push fix ASAP
