### ISSUE TITLE
Open project with IntelliJ and Android Studio

### ISSUE THREAD

**Issue by devj3ns** [leoafarias/sidekick#171]
First, I really love this project. Great work!😀 

I use `Android Studio` for all my flutter projects. It would be awesome if more IDEs than `VSCode` and `XCode` were supported.

**Comment by aguilaair** [comment]
Hey!

This was already discussed in #111: https://github.com/leoafarias/sidekick/issues/111#issuecomment-997293272

> The issue with IntelliJ and Android Studio if I remember correctly is that they don't set a PATH, so there is no CLI command we can run to launch it. They also don't have a URL schema which launches them, like vscode://.

> The combination means that Sidekick would have to look for the executable in each machine, but this is platform-specific and not dependable as, for example, intelliJ or AS can be intstalled through toolbox or individually.

> The midpoint would be allowing the user to pick a specific executable, which shouldn't be too horrible to implement.

**Comment by aguilaair** [comment]
This platform logic was, in fact, implemented in Companion (a sister app to Sidekick) in this file: https://github.com/aguilaair/Companion/blob/94fb8d0af255ae0558896b15858cb333a42c1683/lib/utils/ide_management.dart#L57

As you can see it is extremely specific and non-dependable as any custom install would immediately render the detection unsufficient.

**Comment by devj3ns** [comment]
Hey @aguilaair, thanks for the prompt response :)

Okay 👍
Unfortunately, I neither have enough time nor experience to make a PR for that, but I am sure someone else has. 

If you don't mind, let's leave this issue open to keep track of the process.

**Comment by aguilaair** [comment]
I'm going to take a quick look to see if we can fit this into 1.0.0 😄

**Comment by aguilaair** [comment]
Welp, it was not that bad 👍

**Comment by devj3ns** [comment]
> Welp, it was not that bad 👍 

Awesome ☺️🥳
