### ISSUE TITLE
[Feature Request] Add support for showing the release notes of a new flutter version

### ISSUE THREAD

**Issue by vanlooverenkoen** [leoafarias/sidekick#2]
**Is your feature request related to a problem? Please describe.**
Right now we can't see the changelog in th fvm GUI.

**Describe the solution you'd like**
- show the changelog in the GUI
- open the github page with the latest release so changes can be reviewed in browser as well

**Comment by leoafarias** [comment]
@vanlooverenkoen revisiting this. I am trying to see what is the best way to implement this. I really like the idea, but when I did research not all versions have release notes
https://flutter.dev/docs/development/tools/sdk/release-notes

Will have to think how to go about this

**Comment by vanlooverenkoen** [comment]
I always go to github to see the release notes:

https://github.com/flutter/flutter/tags

not sure if there is a clean way to fetch these release notes.

**Comment by leoafarias** [comment]
thanks @vanlooverenkoen this helps.

**Comment by vanlooverenkoen** [comment]
I created a GitHub issue manager once. I had problems with the GitHub quota api calls. So I think that will the biggest problem

**Comment by leoafarias** [comment]
Kept it simple for now.
