### ISSUE TITLE
[Feature Request] Add support for multiple flutter project directories

### ISSUE THREAD

**Issue by vanlooverenkoen** [leoafarias/sidekick#3]
**Is your feature request related to a problem? Please describe.**
First of all, I want to say thanks for your amazing work!!!!

We are using fvm for all our projects. And we are also using your mac GUI tool.

For that we were thinking about another feature for the GUI tool. 
I use our macbook at work and at home. To split up our work and personal projects in a separate directory. Right now we can only select 1 directory.

**Describe the solution you'd like**
It would be nice to have an option to add multiple directories.

**Comment by leoafarias** [comment]
Released on version 0.0.8. However, instead of providing the root directory of your projects, it just allows adding the project implicitly
