### ISSUE TITLE
[BUG]: Cannot upgrade on macOS and Windows

### ISSUE THREAD

**Issue by Ahmadre** [leoafarias/sidekick#338]
I cannot upgrade to latest Flutter 3.27.0:

<img width="272" alt="Bildschirmfoto 2024-12-16 um 15 42 46" src="https://github.com/user-attachments/assets/04764247-2220-44a9-b5f0-d31ea013284f" />

The command line window underneeth appears and disappears after couple of seconds :/.

I don't know what's going on... even the Toast tells me that stable was successfully upgraded, but that's not true...

**Comment by Ahmadre** [comment]
Edit: when you uninstall your current version SDK (like `stable`) and re-install it, updates are working again 🤔

**Comment by aguilaair** [comment]
I suspect this is a duplicate of https://github.com/leoafarias/sidekick/issues/280

**Comment by Ahmadre** [comment]
> I suspect this is a duplicate of #280

Thanks! I will close this issue for now and follow the linked issue.
