### ISSUE TITLE
Projects menu shows blank screen

### ISSUE THREAD

**Issue by msarkrish** [leoafarias/sidekick#36]
I installed the sidekick.exe file on my laptop.
I still not completed the FVM setup.
Inside settings In the Projects menu, it shows a blank screen.
![Screenshot (108)](https://user-images.githubusercontent.com/45334931/114504154-075e4c00-9c4c-11eb-807d-7b5d4799dd8b.png)

**Comment by aguilaair** [comment]
@leoafarias this is the same issue I experienced and had not managed to fix
