### ISSUE TITLE
Change Settings screen showing blank screen for projects and packages

### ISSUE THREAD

**Issue by msarkrish** [leoafarias/sidekick#39]
I installed the sidekick.exe file on my laptop.
I still not completed the FVM setup.
In Projects and Packages change settings screen showing a blank screen.

Projects:
![Screenshot (113)](https://user-images.githubusercontent.com/45334931/114553848-b407f000-9c83-11eb-955d-93c0c790888e.png)
![Screenshot (114)](https://user-images.githubusercontent.com/45334931/114553860-b66a4a00-9c83-11eb-93c0-c971cfc6f067.png)

Packages:
![Screenshot (115)](https://user-images.githubusercontent.com/45334931/114554033-e9acd900-9c83-11eb-9f60-45c223885922.png)
![Screenshot (116)](https://user-images.githubusercontent.com/45334931/114554038-eb769c80-9c83-11eb-93fd-336376fbf080.png)

**Comment by leoafarias** [comment]
@msarkrish Can you take me to your "installation process"? Also these blank screens are after you have changed the project path?

**Comment by msarkrish** [comment]
@leoafarias I still not completed the setup for FVM.
I downloaded the sidekick.exe file from today's release of 1.0.0-alpha.4

**Comment by leoafarias** [comment]
@msarkrish Ok that blank screen shows up after you choose the projects path?

**Comment by leoafarias** [comment]
@msarkrish I was not able to replicate this issue. What do you do after downloading the zip of the binaries? Also are you running in developer/admin mode?

**Comment by msarkrish** [comment]
> @msarkrish Ok that blank screen shows up after you choose the projects path?

After clicking change settings, it showing a blank screen.

**Comment by msarkrish** [comment]
> @msarkrish I was not able to replicate this issue. What do you do after downloading the zip of the binaries? Also are you running in developer/admin mode?

1). I downloaded [1.0.0-alpha4](https://github.com/leoafarias/sidekick/releases/tag/1.0.0-alpha.4)

2). I opened the sidekick application by double-clicking the sidekick application which is in the release folder.

Folder screenshot Attached.

![sidekick](https://user-images.githubusercontent.com/45334931/114597117-0b22ba80-9cae-11eb-8e27-2b066f0246a6.PNG)

**Comment by leoafarias** [comment]
@msarkrish The fixes are on Alpha.5
