### ISSUE TITLE
Investigate Command Prompt opening up on project handling

### ISSUE THREAD

**Issue by aguilaair** [leoafarias/sidekick#40]
In windows when a setting is changes or you open the project screen a command prompt opens, presumably to complete a task. However, this should be done in the background.

@leoafarias can you assign me this issue? I'd like to take a look in the coming week, right now I'm quite busy 😄 

Example: 
![image](https://user-images.githubusercontent.com/29983481/114598317-0c45ee80-9c92-11eb-9563-e1dd803a8484.png)

**Comment by leoafarias** [comment]
@aguilaair I believe the issue is on `fvm` I am running a process  to get the Flutter config, instead of getting from the file, because I am trying to do everything through their API. I have `runInShell` to be default, not sure if I have it on false

**Comment by aguilaair** [comment]
runInShell should be false by default... but in that case commands to flutter shouldn't work because the PATH isn't loaded

**Comment by leoafarias** [comment]
I think I know the problem. I am running a `whichSync` to get the path of the global flutter version. I think that is what is opening the shell.

**Comment by aguilaair** [comment]
with this fix we should now be able to open up vscode and other PATH installed IDEs very easily, should I create an issue for that  @leoafarias ?

**Comment by leoafarias** [comment]
Yes
