### ISSUE TITLE
Application open is blank

### ISSUE THREAD

**Issue by workwing** [leoafarias/sidekick#43]
Version 1.0.0.5 (1.0.0.5)
macOS Big Sur 11.2.3
https://github.com/workwing/resource/blob/8ab11cf14aaa0dd88e63f467db10ffcc1aade97b/sidekick.png

**Comment by workwing** [comment]
https://github.com/workwing/resource/blob/8ab11cf14aaa0dd88e63f467db10ffcc1aade97b/sidekick.png

**Comment by aguilaair** [comment]
Hey! The is for filing an issue, have you set up fvm already? Have you used the dmg?

Thanks!

**Comment by leoafarias** [comment]
This issue should have been fixed on 0.0.3 please confirm

**Comment by ToanMobile** [comment]
Confirm version 0.0.4 not fix.
<img width="880" alt="Screen Shot 2021-04-28 at 22 42 31" src="https://user-images.githubusercontent.com/6941388/116432874-275c5500-a873-11eb-967a-b8da9a6b176f.png">
<img width="826" alt="Screen Shot 2021-04-28 at 22 42 37" src="https://user-images.githubusercontent.com/6941388/116432895-2b887280-a873-11eb-8c19-923960f84822.png">

**Comment by leoafarias** [comment]
@ToanMobile Can you go to `General` and reset settings. Select the directory again. Seems like this is a different issue.

**Comment by leoafarias** [comment]
This should have been resolved on the latest release
