### ISSUE TITLE
[Feature Request] pre-built binaries for installation

### ISSUE THREAD

**Issue by samandmoore** [leoafarias/sidekick#5]
hiya! 

thanks so much for this project. it's been really useful to me and my teammates.

**Is your feature request related to a problem? Please describe.**
Sorta.

Using `fvm` to install flutter versions is great, _but_ the fact that installing `fvm` requires dart to be installed is quite painful for automating setup scripts to run for a team of developers. Often a developer will end up in a spot where both the dart used to install fvm and the darts installed within the fvm-installed flutter versions are available on their path. 

**Describe the solution you'd like**
Would you be interested in publishing prebuilt binaries for common OSes, like macos, linux, and windows? Then we could install `fvm` via the binary or even via a homebrew formula that fetches the binary instead of installing from source.

**Describe alternatives you've considered**
Alternatively, you could provide a homebrew formula for `fvm` for users and/or publish prebuilt versions of `fvm` to linux package managers, etc.

**Additional context**
n/a

**Comment by aguilaair** [comment]
Hey! I've opened PR #11, which adds a .MSIX installer for Windows and and pre-built binaries for Linux, so the next version of Sidekick should hopefully include all of the prebuilt binaries

**Comment by aguilaair** [comment]
@leoafarias I believe this can be closed now as pre-built binaries fro Linux, MacOS & Windows are now automatically uploaded to every release
