### ISSUE TITLE
Flutter projects are never found

### ISSUE THREAD

**Issue by herrmartell** [leoafarias/sidekick#53]
**Steps to reproduce**

1. On latest version you go and configure the location of the projects, return to projects view and see nothing. 
2. Close sidekick app
3. Reopen sidekick app
4. Check locations of projects in settings: there is no location set

mac os Big Sur 11.2.3

**Comment by leoafarias** [comment]
Just deployed an update. Let me know if the issue persists.

**Comment by herrmartell** [comment]
I cannot check if this works or not because of [this issue](https://github.com/leoafarias/sidekick/issues/54)

**Comment by leoafarias** [comment]
@herrmartell the referenced issue has been resolved

**Comment by herrmartell** [comment]
@leoafarias That seems to have fixed it. Thanks!
