### ISSUE TITLE
Clicking on Side Navigation Items causes the app to crash 

### ISSUE THREAD

**Issue by osaxma** [leoafarias/sidekick#54]
When I click on any of the two marked items in red circle, the app crashes immediately. 

<img width="803" alt="Screen Shot 2021-04-25 at 7 01 25 PM" src="https://user-images.githubusercontent.com/46427323/116000435-d4776900-a5f8-11eb-92ce-0857a10b61c8.png">

I'm using latest version `0.0.3` on `macOS Big Sur 11.2.3 (20D91)`.  Please let me know if you need additional information. (version `0.0.2` works fine btw).

p.s. I also noticed the master branch is not shown as an installed version.

**Comment by leoafarias** [comment]
Thanks for reporting this, seems that it only happens when the app is built for release.

**Comment by leoafarias** [comment]
This is related to the following problem: https://github.com/tekartik/process_run.dart/issues/36

**Comment by leoafarias** [comment]
For further reference https://github.com/flutter/flutter/issues/76990

**Comment by leoafarias** [comment]
@osaxma This has been resolved
