### ISSUE TITLE
Window needs cert to install package. Not trusted certificate.

### ISSUE THREAD

**Issue by masteradit** [leoafarias/sidekick#60]
I downloaded and tried to run `sidekick-windows-0.0.5.msix` from https://github.com/leoafarias/sidekick/releases. But I got this error:

```This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)```

Here's a screenshot of the window:
![screenshot](https://user-images.githubusercontent.com/39951503/116842238-7c90c180-abf9-11eb-9d46-0579553fc4b2.png)

The `Install` button is also disabled.

**Comment by aguilaair** [comment]
Hey! Yes, we know this is an issue Windows users are having and we'd love to address it, but signed certificates are expensive. For the time being please follow the instructions here: 

https://github.com/aguilaair/Companion/wiki/Installing#installing-with-msix-recommended

**Comment by leoafarias** [comment]
Closing this to keep all windows install issues in the same item #85
