### ISSUE TITLE
"No Flutter Projects Found" when directory is set

### ISSUE THREAD

**Issue by PaulHalliday** [leoafarias/sidekick#61]
Sidekick looks like it'd be a fun tool! Thanks for innovating in this space.

**Issue**
I've set a path inside of a folder named `development` which contains multiple Flutter projects (and other project types, i.e. web, c#, etc).

Navigating to the **Projects** tab doesn't show and/or load any Flutter projects.

<img width="1115" alt="Screenshot 2021-05-03 at 21 18 11" src="https://user-images.githubusercontent.com/19576417/116929025-c0b1af80-ac55-11eb-829c-78714f2d549b.png">
<img width="912" alt="Screenshot 2021-05-03 at 21 17 56" src="https://user-images.githubusercontent.com/19576417/116929035-c27b7300-ac55-11eb-8ce3-2f435ee0e269.png">

I've also tried:

* Placing the "Project" path directly inside of a Flutter project
* Enabling/disabling the FVM only option(s)/advanced.
* Reinstalling Sidekick.

Is there something I've done wrong here?

**Comment by leoafarias** [comment]
@PaulHalliday Can you go to General > and reset the settings and try again.

**Comment by leoafarias** [comment]
@PaulHalliday This issue should have been fixed on the latest release. I will go ahead and close the issue. Feel free to reopen if it persists.

**Comment by Gaoxichao** [comment]
same question
