### ISSUE TITLE
New icon in Big Sur style

### ISSUE THREAD

**Issue by mcorbelli** [leoafarias/sidekick#63]
Obviously this is not a issue. But it wouldn't hurt to have the Big Sur-style app icon

**Comment by leoafarias** [comment]
@mcorbelli is this something you would like to tackle? We have some asset files that I can provide

**Comment by mcorbelli** [comment]
> @mcorbelli is this something you would like to tackle? We have some asset files that I can provide 

Sure, I can take a look at it

**Comment by mcorbelli** [comment]
Let me know if there is still a need

**Comment by aguilaair** [comment]
@mcorbelli Yes!

**Comment by leoafarias** [comment]
Sorry for the delay. 
https://www.dropbox.com/t/iW3F1C7kzMahHNQW
 There is a 3D icon that might be a great start.

**Comment by mcorbelli** [comment]
> Sorry for the delay. 
> https://www.dropbox.com/t/iW3F1C7kzMahHNQW
>  There is a 3D icon that might be a great start.

ok, I start looking at it in the next few days

**Comment by leoafarias** [comment]
@mcorbelli we are getting ready for a 1.0 release. Please let me know if this is still something you might get to it, so we can add it to 1.0
