### ISSUE TITLE
[VSCode] - Have to locate SDK on myself

### ISSUE THREAD

**Issue by Ahmadre** [leoafarias/sidekick#64]
I installed newest version of sidekick and fvm, but after I set the version for my project, VSCode is not able to locate the SDK.

Any idea why?

**Comment by aguilaair** [comment]
Hey!

This is a FVM related issue more than a Sidekick issue. However, please open settings in VSCode and look for `dart.flutterSdkPaths`. Then, add where the SDK versions are located, for example I have set it to `/Users/eduardo/fvm/versions`

**Comment by leoafarias** [comment]
@Ahmadre I suggest taking a look at the following docs
https://fvm.app/docs/getting_started/configuration

**Comment by Ahmadre** [comment]
> @Ahmadre I suggest taking a look at the following docs
> https://fvm.app/docs/getting_started/configuration

It works ✨

Thank you for the link :))

**Comment by leoafarias** [comment]
Now that fvm UI is called sidekick seems like this will be a common problem, that the use of fvm under is not clear. I Will add this to the backlog
