### ISSUE TITLE
[Feature Request] General Build Instructions for Windows, Linux, Etc.

### ISSUE THREAD

**Issue by Greendogo** [leoafarias/sidekick#7]
**Is your feature request related to a problem? Please describe.**
I'd like to build fvm for my environment using a simple set of instructions.

**Describe the solution you'd like**
Following the instructions produces a properly built binary of fvm for deployment on an endpoint.

**Comment by leoafarias** [comment]
Will close this issue, we have install instructions and also for FVM we have updated docs here https://fvm.app

**Comment by aguilaair** [comment]
@leoafarias can you maybe create a sub domain e.g. sidekick.fvm.app so we can add the docs for sidekick there?
