### ISSUE TITLE
Why the version in pubspec.yml (0.0.3) vs version.dart (0.0.2) not the same?

### ISSUE THREAD

**Issue by anticafe** [leoafarias/sidekick#70]

**Comment by leoafarias** [comment]
The version is set during the release process. This discrepancy is only on dev, and we will improve to make sure it's consistent even on dev

**Comment by aguilaair** [comment]
One Idea I had to solve this was to push a commit changing the version automatically on a version release. I'm using this successfully for a NextJS site, so I don't see why this wouldn't work in this case

**Comment by leoafarias** [comment]
@aguilaair that is an option. Also, I am having a similar problem on my other packages that use build_version, I think we should use build_version, or create a script through the grinder, or a dart script to make sure we can have the same functionality locally. The CI should call build_version or the script
