### ISSUE TITLE
"Sidekick" can't be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by LautaroLobo12** [leoafarias/sidekick#78]
When I'm trying to install sidekick on my MacBook Pro, this pop-up arises that says: 

> "Sidekick" can't be opened because Apple cannot check it for malicious software.
> 
> This software needs to be updated. Contact the developer for more information.
> 
> This item is on the disk image “sidekick-macos-0.0.6.dmg”.

I would ❤️  to use Sidekick, I just simply can't. 

I'm new to Mac, maybe I missed something... any ideas?

**Comment by leoafarias** [comment]
Please look into https://github.com/leoafarias/sidekick/issues/49, but will leave it open so I can update the documentation.

**Comment by leoafarias** [comment]
Closing this as @aguilaair has already documented here https://github.com/leoafarias/sidekick/blob/main/INSTALLING.md
