### ISSUE TITLE
[Bug] 1.0.0-alpha.2+1 is having an issue with the projects folder

### ISSUE THREAD

**Issue by vanlooverenkoen** [leoafarias/sidekick#8]
A flutter crash is happening on the project page on 1.0.0-alpha.2+1

This is probably an index out of bounds error
![image](https://user-images.githubusercontent.com/21172855/112489474-c2e33d00-8d7e-11eb-8105-e551dafbef75.png)

**Comment by leoafarias** [comment]
@vanlooverenkoen any further information you can provide on this it would be great, as I am not seeing it. For logs you can build the project locally to see the error.

**Comment by vanlooverenkoen** [comment]
I will try to do that tomorrow or during the weekend

**Comment by leoafarias** [comment]
I have found the issue, it can happen when the projects folder changes or some information is missing in the project. Will send a PR

**Comment by leoafarias** [comment]
This has been fixed on the latest versions
