### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by leoafarias** [leoafarias/sidekick#81]
The Flutter community is very much global. It would be important for us to have a path towards internationalization where people could contribute.

Right now Sidekick does not have any abstraction for internalization. We would first need to build this and call for the community to contribute.

**Comment by aguilaair** [comment]
#95 added intl, will be released in next version

**Comment by leoafarias** [comment]
I believe this was a first go. However not sure how maintainable this will be going forward. I believe we need to implement something like https://github.com/aloisdeniel/flutter_sheet_localization, in order to make it easy to create and maintain new languages.

The first issue that I had is when creating new features we have to easily make the strings that need to be translated available. By having a google sheets interface I believe it can be easier, for us to make a “CSV”available that can be versioned, and/or allow for people to modify through the Google sheets itself.

**Comment by MaxiTechno1ogy** [comment]
Have a look at the extension that makes the development a bit easier.

Also there are some websites where you can upload the arb files. And then they can be translated by everyone.

https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl

**Comment by MaxiTechno1ogy** [comment]
https://localizely.com/

**Comment by leoafarias** [comment]
@MaxiTechno1ogy do you have experience with this service? It seems pretty good.

**Comment by robsonsilv4** [comment]
If help about it:
https://localizely.com/flutter-localization-workflow/
https://localizely.com/flutter-over-the-air/

But I still prefer local .arb files:
https://flutter.dev/docs/development/accessibility-and-localization/internationalization
https://github.com/VeryGoodOpenSource/very_good_cli

**Comment by Ahmadre** [comment]
I've got good experiences with internationalization.

Should I create a PR based on i18Next?

It's for me the best way to add translations and to handle Dates, and so on.

**Comment by leoafarias** [comment]
@Ahmadre that would be great, to be honest, I think we need some support on keeping up with localization. We have currently implemented some, but seems that maintaining might be difficult, and also  I think some things could be simpler.

- How do we handle updates to new strings or features
- How do we make people aware that a change needs to happen
- How do make onboarding of new localization easier, where non-programmers can contribute to it
- What are the benefits of using a package, vs. a third-party service.

I don't expect you to answer all of these, but it's some of the questions I have as we bring more localization options.

**Comment by Ahmadre** [comment]
Let's go:

- **How do we handle new strings/features**: ✅ (possible solution from existing production apps will follow)
- **How do we make people aware that a change needs to happen**: What exactly has this to do with translations? I think here of a kind of linter solution / static analysis, if a user tries to add static Text like: `Text('Static text)'`.
- **How do make onboarding of new localization easier, where non-programmers can contribute to it**: ✅ (super easy and convinient possible solution from existing production apps will follow) -> only the translation file (e.g.: `de-DE`, `en-GB`,...) and a new entry in supportedLanguages are needed and that's just a simple line: `const Locale('de', 'DE'),`.
- **What are the benefits of using a package, vs. a third-party service**: I have investigate and do a little research here. Me for myself I didn't like the services from Google Translator API and DeepL API. Especially the DeepL and DeepL Pro Service isn't the yellow of the egg. There're also Google Play Translation Service and others, but like I said, I have to investigate here more in Third party services. It also depends on the project and complexity! And for sidekick I would prefer a package which rich features (Plurals, nesting, contexting/namespacing,...).

If you like I would start tomorrow with the PR while we're discussing all of this.

**Comment by aguilaair** [comment]
@Ahmadre this looks great, thanks!

You're more than welcome to start working on a PR.

Regarding state management, we use Riverpod.

**Comment by leoafarias** [comment]
@Ahmadre Thanks for the detailed answers. I think what you are proposing makes translation much easier, and also maintenance of new translations. Let me know if you would like to get on a chat, or feel you have enough to start a PR

**Comment by Ahmadre** [comment]
I've finished everything and added also spanish as a new language so you can see what I actually did.

**Comment by aguilaair** [comment]
@Ahmadre I cannot get the intl to work on my PC. Is there any step I have to take?

![image](https://user-images.githubusercontent.com/29983481/129089145-dcd5200a-cd5a-4fe3-a3e6-ddb920de1ff4.png)

**Comment by Ahmadre** [comment]
> @Ahmadre I cannot get the intl to work on my PC. Is there any step I have to take?
> 
> ![image](https://user-images.githubusercontent.com/29983481/129089145-dcd5200a-cd5a-4fe3-a3e6-ddb920de1ff4.png)

That doesn't look like intl. Could you reset your settings in SettingsScreen and let Hive reinitialize itself? 

 I am also investigating into this. I also found a problem with 'isCached'. I think null-safety would be helpful.

**Comment by Ahmadre** [comment]
I will rename the key for hive to cache. It can collide with the existing key I was using for the actual locale

**Comment by Techno-Disaster** [comment]
I was recently looking up how the app is setup and would prefer if the keys for the localization strings are typed. If we follow the default flutter internalisation way we could just L10n.of(context).stringToBeTranslated(parameters). But this would probably be a very big refactoring now. Is this worth a new issue?

**Comment by aguilaair** [comment]
I think the effort is not worth it at the moment, with Sidekick being mostly stable and no need to keep adding translations. 

I agree a strongly typed solution would be preferable, so it may be worth it in the long term.
