### ISSUE TITLE
Null-Safety Migration

### ISSUE THREAD

**Issue by aguilaair** [leoafarias/sidekick#82]
What needs to be done to migrate to null safety?
What are the dependencies that still have not migrated yet?

**Comment by leoafarias** [comment]
@aguilaair I believe the dependencies have been updated and its ready to start with a null migration. However just a brief review on the automatic migration suggestion, I suggest not using that, and just switching the SDK, and going through the linter in the following order:

- DTOs
- Services
- Providers
- Atoms
- Molecules
- Organisms
- Screens

**Comment by leoafarias** [comment]
Will be tackling this one
