### ISSUE TITLE
Use Inno for creation of standalone .exe

### ISSUE THREAD

**Issue by DonnC** [leoafarias/sidekick#83]
Hie, @leoafarias  this is a continuation of issue raised here #1

I have been experimenting with flutter desktop for sometime and creating a single .exe has been a pain. Luckily i found a free installer [inno setup](https://jrsoftware.org/isinfo.php) as mentioned in [flutter docs](https://flutter.dev/desktop#building-your-own-zip-file-for-windows) .

The advantage of this is that, it creates a bundled .exe file which can be shared as a single file, it comes with a graphical wizard to setup and also a script that you then run and it compiles to create your .exe
I have downloaded the sidekick and used inno setup to create a standalone .exe 

Here is an example script i used to generate the .exe file (auto generated by Inno setup script wizard) available as [gist here](https://gist.github.com/DonnC/af2f1a91fafdb6a8463878b570904d2f)

The example executable file created,
![image](https://user-images.githubusercontent.com/47761288/119778706-20ebe800-bec8-11eb-9507-a0c3b846d131.png)

**Comment by aguilaair** [comment]
The main issue I see with Inno is the fact that it has to be done manually, and there is no "easy" way to create the installer using Github Actions

**Comment by leoafarias** [comment]
@DonnC would like to help to implement this as part of our creation workflow, also what is the main benefits of Inno vs Msix, and also their certificate signing

**Comment by aguilaair** [comment]
The app is now on the MS Store

https://www.microsoft.com/store/productId/9NZ54K8CW0WG

and has  a signed installer: https://github.com/leoafarias/sidekick/releases/download/0.2.0/windows-signed-0.2.0.Msix

I see no need for alternative install methods at this time
