### ISSUE TITLE
MS Windows needs cert to install

### ISSUE THREAD

**Issue by fredgrott** [leoafarias/sidekick#85]
MS just switched out their install permissions oper the new MS OS update,

You now need to include a cert in installer for most users to install it on MS Windoes

**Comment by aguilaair** [comment]
This is a known issue, please check https://github.com/leoafarias/sidekick/blob/main/INSTALLING.md#installing-with-msix-recommended

If you still have an issue let me know

**Comment by aguilaair** [comment]
Duplicate #60

**Comment by leoafarias** [comment]
Close because as @aguilaair mentioned is a duplicate
