### ISSUE TITLE
Failed installing msix Windows 10

### ISSUE THREAD

**Issue by andgar2010** [leoafarias/sidekick#86]
Haved a problem install msix but I already did with the certification installation instructions.

![image](https://user-images.githubusercontent.com/19521054/121216883-ecbce380-c846-11eb-98ac-64960401af59.png)

Check Event Logs:
![image](https://user-images.githubusercontent.com/19521054/121209975-e9265e00-c840-11eb-8d3f-8d0ae4e17ab0.png)

https://docs.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting?redirectedfrom=MSDN
![image](https://user-images.githubusercontent.com/19521054/121210175-13781b80-c841-11eb-9cc2-dc1e32b8083b.png)

AppXDeployment-Server event log:
app.fvm.sidekick_0.0.8.0_x64__pjyac4g0caf2w (sidekick-windows-0.0.8.msix) C:\\?\Volume{634b00df-ab47-43c7-9c7b-b83ca2e2c569}A @NULLRuntimeBroker.exeappreputationhelpers.cpp,168,8000FFFF;approvalstatehandler.cpp,95,8000FFFF;deploymentmanager.cpp,264,8000FFFF;deploymentrequest.cpp,1959,8000FFFF;deploymentrequest.cpp,2104,8000FFFF;errorhelpers.cpp,54,8007029C;errorhelpers.cpp,54,8007029C;deploymentrequest.cpp,4014,8000FFFF;[{GetErrorInfo reports there is no error object to return}];Dfile:///C:/Users/user/Downloads/sidekick-windows-0.0.8.msix

**Comment by aguilaair** [comment]
I'm investigating this

**Comment by aguilaair** [comment]
I'm assuming you have installed the certificate, right @andgar2010 ?

**Comment by aguilaair** [comment]
Please try adding the MSIX as an exception to windows defender (source: https://www.reddit.com/r/sysadmin/comments/cr6uvt/multiple_msix_packages_failing_to_install/)

**Comment by subzero911** [comment]
@andgar2010 use .zip archive, it contains exe file.
Msix actually doesn't work.

**Comment by aguilaair** [comment]
> 
> 
> @andgar2010 use .zip archive, it contains exe file.
> Msix actually doesn't work.

Hey,

MISX should work fine as long as you have installed the certificate, could you describe your issue? I've been using the MSIX version for various months, and just trued a clean install with no issues whatsoever.

Thanks!

**Comment by andgar2010** [comment]
> 
> 
> I'm assuming you have installed the certificate, right @andgar2010 ?

Sorry for the late reply, I have already installed the certificate according to the instruction.

**Comment by andgar2010** [comment]
> exception



> 
> 
> Please try adding the MSIX as an exception to windows defender (source: https://www.reddit.com/r/sysadmin/comments/cr6uvt/multiple_msix_packages_failing_to_install/)

I have already tried to exception Windows Defender, but not could because my user role is administrator, but some configuration restrictions as antivirus because it is a corporate computer.

**Comment by andgar2010** [comment]
> 
> 
> @andgar2010 use .zip archive, it contains exe file.
> Msix actually doesn't work.

Right, I used zip, but some limited functions than MSIX.

**Comment by aguilaair** [comment]
> I have already tried to exception Windows Defender, but not could because my user role is administrator, but some configuration restrictions as antivirus because it is a corporate computer.

Could you try installing another MSIX and see it if works?

**Comment by andgar2010** [comment]
> Could you try installing another MSIX and see it if works?
@aguilaair 

I was testing another MSIX with latest version 0.1.1 and it fails to replicate.
![image](https://user-images.githubusercontent.com/19521054/123716444-31351100-d840-11eb-8fea-c4eef0306da5.png)

**Comment by fredgrott** [comment]
this may be separate or related. In my recent attempt, the install button is greyed and a mouse-over shows US MSIX testing cert which is most likely why the install button is greyed out.

**Comment by NiceboyWiseboy** [comment]
Hello,

I also have the same issue. Anyone found the solution yet? I tried by installing the solution also. It doesn't work either.
Or someone please tell me how to install the certificate, so I can verify if I'm missing something in installing the certificate.

Thanks for helping...

**Comment by aguilaair** [comment]
Solved, please download Sidekick from the MS Store

https://www.microsoft.com/store/productId/9NZ54K8CW0WG

or use the signed installer: https://github.com/leoafarias/sidekick/releases/download/0.2.0/windows-signed-0.2.0.Msix
