### ISSUE TITLE
[Feature Request] In app updates

### ISSUE THREAD

**Issue by vanlooverenkoen** [leoafarias/sidekick#9]
It would be nice to check for updates of sidekick inside the app so we don't have to go to the github page to check for new updates.

The download & installation of a gui update could also happen from the gui

**Comment by aguilaair** [comment]
Hey! 

This will be coming very soon, I'm migrating all the Companion stuff to this repo, which includes auto updates!

Just a quick demo:
![20210325_160726.jpg](https://user-images.githubusercontent.com/29983481/112495509-3e93b880-8d84-11eb-9b93-425df6e68d5f.jpg)

**Comment by aguilaair** [comment]
@leoafarias this has been implemented in https://github.com/leoafarias/sidekick/releases/tag/1.0.0-alpha.3, can it be closed?

**Comment by leoafarias** [comment]
@aguilaair did have time to do proper testing on windows and Linux.

**Comment by leoafarias** [comment]
Will test as soon as we have windows automation working

**Comment by aguilaair** [comment]
Its working ok in Companion, and its basically the same code, might need to tweak some stuff on Linux still because we have mo installer

**Comment by msarkrish** [comment]
@leoafarias @aguilaair Today I installed Sidekick 1.0.0-alpha.4 in my windows.
New version 1.0.0-alpha.5 now available but the new version available pop up not showing for me.

**Comment by aguilaair** [comment]
@leoafarias disabled it unfortunately

**Comment by leoafarias** [comment]
@msarkrish There will be changes on the URL scheme for builds and we might adjust the checking, which will cause the check update to break.

This will also probably include a reset of the versions to 0.0.1 instead of 1.0.0-alpha.6 for example.

**Comment by msarkrish** [comment]
@leoafarias then this issue should be open right?

**Comment by leoafarias** [comment]
This is on the next release
