### ISSUE TITLE
Not working with VSCode

### ISSUE THREAD

**Issue by subzero911** [leoafarias/sidekick#92]
I installed several versions of Flutter via Sidekick (along with existing installation in D:\Flutter\Flutter SDK)
I set up version 2.2.2 globally. I also set version 2.2.2 to my project (in Projects tab)
When I open the project in VSCode, it still uses version 1.22.6 (from D:\Flutter\Flutter SDK path).

```bash
$ flutter doctor -v
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.1052], locale ru-RU)
    • Flutter version 1.22.6 at D:\Flutter\Flutter SDK
    • Framework revision 9b2d32b605 (5 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at D:\Android_SDK
    • Platform android-30, build-tools 30.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

My PATH (maybe should I tweak it?)
![image](https://user-images.githubusercontent.com/12999702/122247213-df030000-cecf-11eb-9bf0-7ae546e29461.png)
![image](https://user-images.githubusercontent.com/12999702/122247271-e75b3b00-cecf-11eb-8265-df309fabdf69.png)

**Comment by leoafarias** [comment]
@subzero911 Please read the following https://fvm.app/docs/getting_started/configuration#ide, this is an FVM question. If the link above does not help you please open an issue on the fvm repo
