### ISSUE TITLE
Ui Issues

### ISSUE THREAD

**Issue by ricbermo** [leoafarias/sidekick#93]
I recorded [this](https://www.loom.com/share/953bf7a12f204a10b108a7e2010000ef) video.

1. When using the dark theme, the top and left bars are not updated.
2. When you close a release details section, it breaks the UI.

Let me know if you need my help figuring out what's not working.

**Comment by leoafarias** [comment]
@ricbermo This should have been solved on the latest version. Could you try 0.0.9 and please let me know if the issue persists?

**Comment by ricbermo** [comment]
@leoafarias #2 was fixed. #1 not. IDK if that's an issue or that's how it's supposed to work.

![image](https://user-images.githubusercontent.com/2601363/122263602-3f784a00-ce9c-11eb-9fab-17f95f9ee69e.png)

**Comment by leoafarias** [comment]
Fix has been merged
